name: Run Azure Login with OpenID Connect
on: 
  workflow_dispatch:
  pull_request:
    branches:
        - main

permissions:
  id-token: write
  contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

    - name: 'Az CLI login'
      uses: azure/login@v2.1.0
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800
      with:
        terraform_wrapper: false

    - name: 'Terraform Format'
      id: fmt
      run: terraform fmt 

    - name: 'Terraform Init'
      id: init
      run: terraform init
      
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan

