name: 'Terraform GitHub Action'
on:
    pull_request:
        branches:
            - main
            
permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        name: Terraform
        env:
            ARM_USE_OIDC: true
            # ARM_OIDC_TOKEN: ${{ secrets.AZURE_CREDENTIALS }}
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            # ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            # ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        runs-on: ubuntu-latest
        steps:            
            - name: Checkout
              uses: actions/checkout@v4

            # - name: Log in with Azure
            #   uses: azure/login@v1
            #   with:
            #     creds: '${{ secrets.AZURE_CREDENTIALS }}'
              
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Format
              id: fmt
              run: terraform fmt -check

            - name: Terraform Init
              id: init
              run: terraform init

            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color

            - name: Terraform Plan
              id: plan
              run: terraform plan -no-color